export const OPSCLAW_APP_NAME = 'OpsClaw';
export const OPSCLAW_WINDOW_WIDTH = 1440;
export const OPSCLAW_WINDOW_HEIGHT = 920;
export const OPSCLAW_BACKEND_READY_TIMEOUT_MS = 15_000;
export const OPSCLAW_BACKEND_POLL_INTERVAL_MS = 250;
export const OPSCLAW_BACKEND_SHUTDOWN_TIMEOUT_MS = 5_000;
