import type { SavedConnectionGroup } from '@/features/workbench/types';

export const savedConnectionGroups: SavedConnectionGroup[] = [
  {
    id: 'prod-redis',
    name: 'Production / Redis',
    isDefault: false,
    profiles: [
      {
        id: 'redis-master-02',
        name: 'redis-master-02',
        groupId: 'prod-redis',
        group: 'Production / Redis',
        jumpHostId: null,
        host: 'redis-master-02.internal',
        port: 22,
        username: 'root',
        authMode: 'password',
        note: 'master / sh-a / 38ms',
      },
      {
        id: 'db-replica-07',
        name: 'db-replica-07',
        groupId: 'prod-redis',
        group: 'Production / Redis',
        jumpHostId: null,
        host: 'db-replica-07.internal',
        port: 22,
        username: 'root',
        authMode: 'password',
        note: 'replica / disk 92% / 52ms',
      },
      {
        id: 'db-replica-08',
        name: 'db-replica-08',
        groupId: 'prod-redis',
        group: 'Production / Redis',
        jumpHostId: null,
        host: 'db-replica-08.internal',
        port: 22,
        username: 'root',
        authMode: 'password',
        note: 'replica / healthy / 44ms',
      },
    ],
  },
  {
    id: 'prod-market-core',
    name: 'Production / Market-Core',
    isDefault: false,
    profiles: [
      {
        id: 'web-gateway-11',
        name: 'web-gateway-11',
        groupId: 'prod-market-core',
        group: 'Production / Market-Core',
        jumpHostId: null,
        host: 'web-gateway-11.internal',
        port: 22,
        username: 'ops',
        authMode: 'password',
        note: 'edge / failed unit / 31ms',
      },
      {
        id: 'schedule-prod-a',
        name: 'schedule-prod-a',
        groupId: 'prod-market-core',
        group: 'Production / Market-Core',
        jumpHostId: null,
        host: 'schedule-prod-a.internal',
        port: 22,
        username: 'ops',
        authMode: 'password',
        note: 'scheduler / healthy / 27ms',
      },
    ],
  },
];

export const batchExecutionRows = [
  {
    node: 'redis-master-01',
    service: 'healthy',
    disk: '58%',
    latency: '29ms',
    tone: 'ok',
    status: 'ok',
  },
  {
    node: 'redis-master-02',
    service: 'healthy',
    disk: '62%',
    latency: '38ms',
    tone: 'ok',
    status: 'ok',
  },
  {
    node: 'db-replica-05',
    service: 'healthy',
    disk: '72%',
    latency: '46ms',
    tone: 'warn',
    status: 'watch',
  },
  {
    node: 'db-replica-07',
    service: 'degraded',
    disk: '92%',
    latency: '52ms',
    tone: 'err',
    status: 'critical',
  },
  {
    node: 'db-replica-08',
    service: 'healthy',
    disk: '69%',
    latency: '44ms',
    tone: 'ok',
    status: 'ok',
  },
];
